spring.data.redis.host=localhost
spring.data.redis.port=6379

rate.limit.free.capacity=5
rate.limit.free.refill.interval.seconds=3600

rate.limit.premium.capacity=12
rate.limit.premium.refill.interval.seconds=2700
